
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab1(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
assign LEDR[0] = KEY[0] ^ SW[0];
assign LEDR[1] = KEY[0] ^ SW[1];
assign LEDR[2] = KEY[0] ^ SW[2];
assign LEDR[3] = KEY[0] ^ SW[3];
assign LEDR[4] = KEY[0] ^ SW[4];
assign LEDR[5] = KEY[0] ^ SW[5];
assign LEDR[6] = KEY[0] ^ SW[6];
assign LEDR[7] = KEY[0] ^ SW[7];

assign LEDR[9:8] = SW[9:8];



//=======================================================
//  Structural coding
//=======================================================
Birthday U1(.HEX0(HEX0), .HEX1(HEX1), .HEX2(HEX2), .HEX3(HEX3), .HEX4(HEX4), .HEX5(HEX5), .KEY(KEY));


endmodule
